<?php
/**
/UIS okkela Theme templates html topmenu.
/@author Vladislav Romaniuk vromaniuk@ukrinsoft.net
/@copyright 2020 Vlromaniuk
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>

<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"><?php echo _('Flash Deal Products') ?> </span>
    </h1>
</div>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $item ) :?>
            
            <?php $_product = $this->getFullProduct($item); ?>
                
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <div>

                        <?php
                            $specialprice = $_product->getSpecialPrice();
                            $specialPriceFromDate = $_product->getSpecialFromDate();
                            $specialPriceToDate = $_product->getSpecialToDate();    
                            $today = time();
                            $price = $_product->getPrice();
                            if($price){
                                $sale = round((($price-$specialprice)/$price)*100);
                            }
                            if ($specialprice) {
                                if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
                                    <div class="label-product label-sale">
                                        <span class="sale-product-icon">
                                            -<?php if($sale) { echo $sale.'%'; } else {echo __('Sale');} ?>
                                        </span>
                                    </div>
                                <?php }
                            }
                        ?>

                        </div>
                        <p class="description">
                    	    <?php /* @noEscape */  //$_helper->productAttribute($_product, $_product->getShortDescription(), 'description'); ?>
                            <span class="sku">SKU <?= /* @noEscape */ $_product->getSku() ?></span>
                        </p>
                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?= $_product->getEntityId(); ?> " data-price-box="product-id-<?= $_product->getEntityId(); ?>">
                                        <span class="special-price">
                                            <span class="price-container price-final_price tax weee">
                                                <span class="price-label">As low as</span>
                                                <span id="product-price-<?= $_product->getEntityId(); ?>" data-price-amount="<?= $_product->getFinalPrice(); ?>" data-price-type="finalPrice" class="price-wrapper">
                                                <?php 
                                                    $price = $_product->getFinalPrice();  
                                                    
                                                    if ($_product->getIsFlashdeal() && $_product->getFlashdealId()) {
                                                        $flashdealId = $_product->getFlashdealId(); 
                                                        $flashdealProductData  = $this->getFlashdealProductData($flashdealId);

                                                        if (isset ($flashdealProductData['flashdeal_product_requested_price'])) {
                                                            $price = (int)$flashdealProductData['flashdeal_product_requested_price'];
                                                        }
                                                    } 
                                                ?>

                                                    <span class="price"><?php echo $this->getFormattedPrice( $price ); ?></span>

                                                </span>
                                            </span>
                                        </span>
                                    </div>
                        <?php /**                                     
                        <?=  $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?=  $block->getProductPrice($_product) ?>  
                        **/ ?> 
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
